from django.urls import path
from . import views
urlpatterns=[
 path('',views.home,name='home'),path('login/',views.login_view,name='login'),path('logout/',views.logout_view,name='logout'),path('register/',views.register,name='register'),
 path('catalog/',views.catalog,name='catalog'),path('product/<int:pk>/',views.product_detail,name='product_detail'),
 path('cart/',views.cart,name='cart'),path('cart/add/<int:pk>/',views.add_to_cart,name='add_to_cart'),path('cart/update/<int:pk>/',views.update_cart,name='update_cart'),path('cart/remove/<int:pk>/',views.remove_from_cart,name='remove_from_cart'),
 path('wishlist/',views.wishlist,name='wishlist'),path('wishlist/toggle/<int:pk>/',views.toggle_wishlist,name='toggle_wishlist'),path('coupon/apply/',views.apply_coupon,name='apply_coupon'),
 path('profile/',views.profile,name='profile'),path('notifications/',views.notifications,name='notifications'),path('checkout/',views.checkout,name='checkout'),path('order/<int:pk>/',views.order_detail,name='order_detail'),path('order/<int:pk>/cancel/',views.cancel_order,name='cancel_order'),path('order/<int:pk>/review/',views.review_create,name='review_create'),path('receipt/<int:pk>/',views.receipt_pdf,name='receipt_pdf'),path('my-orders/',views.my_orders,name='my_orders'),
 path('admin-dashboard/',views.admin_dashboard,name='admin_dashboard'),path('admin/products/',views.admin_products,name='admin_products'),path('admin/products/add/',views.admin_product_add,name='admin_product_add'),path('admin/products/<int:pk>/edit/',views.admin_product_edit,name='admin_product_edit'),path('admin/products/<int:pk>/delete/',views.admin_product_delete,name='admin_product_delete'),path('admin/orders/',views.admin_orders,name='admin_orders'),path('admin/orders/<int:pk>/status/',views.admin_order_status,name='admin_order_status'),path('admin/inventory/',views.admin_inventory,name='admin_inventory'),path('admin/coupons/',views.admin_coupons,name='admin_coupons'),path('admin/weavers/',views.admin_weavers,name='admin_weavers'),path('admin/categories/',views.admin_categories,name='admin_categories'),path('admin/categories/<int:pk>/toggle/',views.admin_category_toggle,name='admin_category_toggle'),path('admin/customers/',views.admin_customers,name='admin_customers'),path('admin/customers/<int:pk>/edit/',views.admin_customer_edit,name='admin_customer_edit')]
